[package]
name = "exchange-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
backend.workspace = true
chrono.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
uuid.workspace = true

[dev-dependencies]
anyhow.workspace = true
exchange-test-utils.workspace = true
tokio-test.workspace = true
