[package]
name = "schema-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
backend = { path = "../../apps/backend", features = ["schema"] }
schemars.workspace = true
serde_json.workspace = true
